### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ColinBe95** [EcovadisCode/charts#45]
Hey, I think there is a typo here:
https://github.com/EcovadisCode/charts/blob/master/charts/dotnet-core/templates/deployment.yaml#L134

I don't think it's supposed to be 
.Values.global.additionalValumesEnabled
but rather
.Values.global.additionalVolumesEnabled

Also [here](https://github.com/EcovadisCode/charts/blob/master/charts/dotnet-core/templates/deployment.yaml#L157) and [here](https://github.com/EcovadisCode/charts/blob/master/charts/dotnet-core/templates/deployment.yaml#L187) and [here](https://github.com/EcovadisCode/charts/blob/master/charts/dotnet-core/values.yaml#L149)

**Comment by ColinBe95** [comment]
Also I think there is quotes missing here:
https://github.com/EcovadisCode/charts/blob/master/charts/dotnet-core/values.yaml#L93

**Comment by SzymonSt** [comment]
Will fix the typo thanks for noticing,
